spring:
  application:
    name: employee-service

server:
  servlet:
    context-path: /employee-service
  port: 8080

employee:
  page:
    size: 2

custom:
  property:
    int: 24
    string: Welcome to Gyan Darpan
    boolean: true
    fruits: apple,banana,orange
    fruits1: apple;banana;orange

user:
  user-name: Gyan Darpan
  age: 1
  active: true
  roles:
    - ADMIN
    - USER
    - MODERATOR
  address:
    street: 123,ABC
    city: Delhi
    country: India


email:
  gmail:
    host: "smtp.gmail.com"
    port: 587
    username: "demo"
    password: "password1"
  outlook:
    host: "smtp.outlook.com"
    port: 587
    username: "outlookUser"
    password: "password2"
