spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_service
    username: springboottutorial
    password: springboottutorial
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: employee-service-connection-pool
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000

server:
  servlet:
    context-path: /employee-service
  port: 8080

employee:
  page:
    size: 2

